### ISSUE TITLE
Run compose/decompose on pre push|post pull hooks

### ISSUE THREAD

**Issue by AllanOricil** [mcarvin8/sf-decomposer#13]
Command would run automatically if sfdx-project.json has a prop that tells the plugin hook to run. 

Hook is called, if prop = true, Command runs when extracting(decompose) or deploying(compose) metada.

Obs: If sfdx does not provide such hooks I can open a PR on the repo.

**Comment by mcarvin8** [comment]
I like the idea @AllanOricil. It does look we can configure hooks to run post-retrieval (for the "decompose" command) and run pre-deploy (for the "compose" command), which would definitely be a neat way to optimize the use of this plugin with the CLI. 

https://developer.salesforce.com/docs/atlas.en-us.sfdx_cli_plugins.meta/sfdx_cli_plugins/cli_plugins_customize_hooks_list.htm

My one concern would be how we would allow a specific user to modify the hook (probably in the sfdx-project.json) so it only fires for the specific metadata types they wish to use this plugin for.

**Comment by mcarvin8** [comment]
I currently don't see any indication of this level of customization in the docs for plugin hooks. 

Ideally, I think the desired implementation for this plugin would be:

- Define post-retrieval and pre-deploy hooks for all supported metadata types
- Have a condition that checks the sfdx-project.json for a unique section for this plug-in and:
   - if a specific key isn't provided in the JSON file, either don't fire any hooks or fire all hooks for all metadata types (not sure which one is a better default condition)
   - fire hooks for the specific metadata types defined in the JSON

Perhaps we should raise a ticket with the Salesforce CLI team to provide this level of customization for hooks?

**Comment by AllanOricil** [comment]
@mcarvin8 I think you have to create your own. But it would be a good feature for oclif plugins. Vscode API has such a thing. 

@scolladon I believe he created config prop parser and file name for his plugin

**Comment by scolladon** [comment]
@AllanOricil is right, I read the `sfdx-project.json` to [find](https://github.com/scolladon/sfdx-git-delta/blob/2d1b00eb18cde82553ebc4a1a49e0404183d6025/src/utils/cliHelper.ts#L131C54-L131C76) a special prop and use it in `sfdx-git-deta`.

**Comment by mcarvin8** [comment]
Latest release now reads the `sfdx-project.json` file for package directories, which allows the decomposer to process multiple package directories at once and removes the need to do anything additional for this task.

This should make implementing hooks easier now since the hook only needs to parse the `sfdx-project.json` for meta suffixes to decompose/recompose. Still need to figure out how to test hooks before building a new release (if possible?). Or I can just make a new `beta` release with the hooks first to confirm.

The 2 hooks should just need to run the default classes similar to how the tests are calling them:

``` typescript
import DecomposerRecompose from '../../../src/commands/decomposer/recompose.js';

    for (const metadataType of metadataTypes) {
      // eslint-disable-next-line no-await-in-loop
      await DecomposerRecompose.run(['--metadata-type', metadataType]);
    }
```

**Comment by mcarvin8** [comment]
Deploy and Retrieve hooks may be broken... https://developer.salesforce.com/blogs/2022/02/we-broke-deploy-retrieve-hooks

**Comment by mcarvin8** [comment]
Also, based on some testing, looks like we might not be able to add extra keys to the `sfdx-project.json` file. SFDX seems to flag keys in the JSON it does not recognize. So we probably would need to a make new JSON file for this plugin to not interfere with the Salesforce CLI.

But I'm not sure if this effort would be worth it if Salesforce has intentionally broken deploy/retrieve hooks in newer versions of the CLI due to wanting to increase CLI times.....

**Comment by AllanOricil** [comment]
> Also, based on some testing, looks like we might not be able to add extra keys to the `sfdx-project.json` file. SFDX seems to flag keys in the JSON it does not recognize. So we probably would need to a make new JSON file for this plugin to not interfere with the Salesforce CLI.
> 
> But I'm not sure if this effort would be worth it if Salesforce has intentionally broken deploy/retrieve hooks in newer versions of the CLI due to them pushing SDR. It also looks like they're pushing SDR updates to support custom registry variants soon to handle decomposing/recomposing certain meta types from the package...

@mcarvin8 you probably have to add your schema changes in this repo. There is a schema for `sfdx-project.json` https://github.com/forcedotcom/schemas

**Comment by mcarvin8** [comment]
The post retrieve hook for decompose has been op-tested and will be shipped with v3.3.5.

I have elected to use environment variables since @salesforce/kit provides some methods to parse env variables. Seemed easier then updating the `sfdx-project.json` schema.

I still need to workout the predeploy hook for the recompose command. Based on https://developer.salesforce.com/blogs/2022/02/we-broke-deploy-retrieve-hooks, it seems like the previous method of changing files before a deployment is impossible with the SDR. I need to figure out an alternative of changing files before deployment.

**Comment by AllanOricil** [comment]
None of the workarounds is good anyway. The idea was to let the User use the standard deploy command and not a custom one to simplify as much as possible. So, I think the best option is wait for the `predeploy` hook to work again. I would ask @shane when they will have it fixed. 

What about opening a PR in the SDR package to enable custom "pre deploy" hooks? The idea is to enable SDR to have any number of custom pre/post deploy hooks, instead of just a single one


````
[pre deploy stage hooks] => deploy => [post deploy stage hooks]
````

Inside a stage hook, there can exist any number of hooks as needed from any number of plugins. When registering a hook to a stage hook, the plugin dev must specify an Index to instruct the the cli the order when its hook must run. Before a hook runs, the list of hooks in a stage is resolved to determine the order hooks will run for that stage. The higher the index, the the earlier the hook runs, because it has "high" precedence. Plugin developers can specify the index of their plugin hook for a particular stage to ease setup, but a User must be able to overwrite in case he has installed 2 plugins that both contain a stage hook with the same index. In this scenario, without enabling the User to configure the order, there wouldn't be a way for the cli to resolve the order of the hooks for a stage.

**Comment by mcarvin8** [comment]
@AllanOricil - Based on how I was reading @mshancemc 's article, the pre-deploy hooks worked originally like

Convert to source format in temp dir --> run pre-deploy hook --> deploy

Since SDR doesn't create a temp dir anymore, there's no where to update the files before they are deployed if the deploy command does the source conversion before running a predeploy hook.

**Comment by mcarvin8** [comment]
I was just playing around with making a custom deploy command and I agree that it's not a good idea to avoid further deviations from the CLI standard. Plus, I would have to worry about deploy fulls, deploy validate, deploy quick, etc. .

**Comment by mcarvin8** [comment]
@AllanOricil - When I clear out the original custom labels file in my branch and attempt to run a deployment of custom labels after adding the `scopedPreDeploy.ts` hook below, I get a `Error (1): No source-backed components present in the package.` error. So I think that confirms you're unable to change the files via pre deploy hook before the deploy runs.

`sf project deploy start --metadata CustomLabels`

``` typescript
import { Command, Hook, Config } from '@oclif/core';
import { ScopedPreDeploy } from '@salesforce/source-deploy-retrieve';
import { env } from '@salesforce/kit';
import DecomposerRecompose from '../commands/decomposer/recompose.js';

type HookFunction = (this: Hook.Context, options: HookOptions) => Promise<void>;

type HookOptions = {
  Command: Command;
  argv: string[];
  commandId: string;
  result?: ScopedPreDeploy;
  config: Config;
};

export const scopedPreDeploy: HookFunction = async function () {
  const postpurge = env.getBoolean('SFDX_DECOMPOSER_POSTPURGE', false);
  const metadataTypes: string = env.getString('SFDX_DECOMPOSER_METADATA_TYPES', '.');
  const format: string = env.getString('SFDX_DECOMPOSER_METADATA_FORMAT', 'xml');

  if (metadataTypes.trim() === '.') {
    return;
  }

  const metadataTypesArray: string[] = metadataTypes.split(',');

  const commandArgs: string[] = [];
  for (const metadataType of metadataTypesArray) {
    const sanitizedMetadataType = metadataType.replace(/,/g, '');
    commandArgs.push('--metadata-type');
    commandArgs.push(sanitizedMetadataType);
  }
  commandArgs.push('--format');
  commandArgs.push(format);
  if (postpurge) {
    commandArgs.push('--postpurge');
  }
  await DecomposerRecompose.run(commandArgs);
};
```

**Comment by mcarvin8** [comment]
I agree with the idea of allowing multiple pre-deploy hooks based on a priority list in the package.json.

But I think we're still unable to proceed with a pre-deploy hook since it cannot change the source files before starting the deploy.

**Comment by AllanOricil** [comment]
Ok 👍
if there is no context in the hook about the files that are going to be deployed, then transformations can't be done. I hope they fix it, or at least create another built-in hook to enable transformations.


I don't think it is a good idea to use env variables to store metadata types the way you did because there is a limit of characters we can store in env variables. Better to store those type of configuration values using your original idea of having your own config file.

**Comment by AllanOricil** [comment]
I would remove dx from the name because sf did for their cli, and use a common convention for config files to make it less difficult for people to remember its name

```
.sfdecomposerrc
.sfdecomposer.config.js
.sfdecomposer.config.json
```

Similar to what other tools did, like prettier. Maybe there is a npm package which already handles any type of config file, and you just need to give it a name, like `sfdecomposer`. I just did not google it.

I hope one day sf cli changes any of these patterns `.sfrc`, `.sf.config.json` , `.sf.config.js` like most of other tooling do

**Comment by mcarvin8** [comment]
Thank you @AllanOricil for your continued support in making this plugin better.

I have switched the post retrieve hook from environment variables and just renamed it to `.sfdecomposer.config.json` file that should be in the repo's root folder.

``` json
{
  "metadataSuffixes": "labels,workflow,profile",
  "prePurge": true,
  "postPurge": true,
  "decomposedFormat": "xml"
}
```

Probably would make sense to rename my plugin to `sf-decomposer` but I'm unclear how renaming NPM packages work (if that will make a brand new instance or if it's smart enough to pick up the name). I know we talked about renaming this plugin in the past.

**Comment by AllanOricil** [comment]
I saw some deprecated package and they all did the following. They publish a deprecated version of the current package, with an updated README as well, to send people to the new package. As an additional step, I think you could also bump its major version.

**Comment by mcarvin8** [comment]
Thanks. This has been renamed to `sf-decomposer` and released @ 4.0.0.

The `sfdx-decomposer` has been marked as deprecated on NPM.

**Comment by AllanOricil** [comment]
@mcarvin8 check if that command that lists plugins to be installed in sf cli is still showing your deprecated plugin. Im not sure if they have considered filtering out deprecated packages.

**Comment by mcarvin8** [comment]
@AllanOricil - seems like it was still showing the plugin installed. You do get a warning now trying to install sfdx-decomposer, but I think they will need to manually uninstall sfdx-decomposer if they have it locally.

`sf plugins uinstall sfdx-decomposer`

I'll make an Issue here on this repo telling people to uninstall the sfdx decomposer manually if they have it before they can use sf-decomposer.

**Comment by mcarvin8** [comment]
@mshanemc - Is pre-deploy hooks that can change source files before deploy going to remain broken for the foreseeable future? Based on your article, you listed it as a breaking change so I'm going to assume yes for now.

**Comment by mcarvin8** [comment]
@AllanOricil - I figured this out. Instead of using a predeploy hook, I created a prerun hook for the recompose command which will only run when the sf command is `project deploy start`/`project deploy validate`. The prerun hook will use the same JSON file as the postretrieve hook.

This works as expected when testing retrievals and deployments locally. Shipped with 4.0.1.

**Comment by AllanOricil** [comment]
Amazing work @mcarvin8 👏
